name: CI

on:
  push:
  pull_request:

jobs:
  host:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: host
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: host
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
