name: CI

on:
  push:
  pull_request:

jobs:
  host:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: midi-tester
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libasound2-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: midi-tester
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings

  firmware:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firmware
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: firmware
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
        name: clippy (receive)
      - run: MODE=receive2 cargo clippy -- -D warnings
        name: clippy (receive2)
      - run: MODE=send cargo clippy -- -D warnings
        name: clippy (send)
      - run: MODE=display cargo clippy -- -D warnings
        name: clippy (display)
      - run: MODE=bpm cargo clippy -- -D warnings
        name: clippy (bpm)
      - run: MODE=nor cargo clippy -- -D warnings
        name: clippy (nor)
      - run: MODE=fram cargo clippy -- -D warnings
        name: clippy (fram)
